title: holoflux
logo: /assets/img/logo.jpg
description: holoflux collective develops transdisciplinary projects that exist beyond the binary. inspired by the holographic and flowing nature of our reality, we create experiences that strive to nuture wholeness amidst this increasingly fractured world we find ourselves in.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
