title: holoflux labs
logo: /assets/img/logo.jpg
description: holoflux labs develops transdisciplinary projects that exist beyond the binary. inspired by the holographic and flowing nature of our reality, we create experiences that strive to nuture wholeness.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
